[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = -v --tb=short

markers =
    usuarios: Todos os testes do endpoint /usuarios
    listagem: Testes de GET
    cadastro: Testes de POST
    busca: Testes de GET por ID
    atualizacao: Testes de PUT
    exclusao: Testes de DELETE
    negativo: Cenários de erro esperado
    login: Testes do endpoint /login
    produtos: Todos os testes do endpoint /produtos
    carrinhos: Todos os testes do endpoint /carrinhos
